services:
  # app:
  #   build: .
  #   container_name: app
  #   depends_on:
  #     - postgres
  #     - redis
  #     # postgres:
  #     #   condition: service_healthy
  #     # redis:
  #     #   condition: service_healthy
  #   ports:
  #     - 9999:9999

  postgres:
    image: postgres #:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U user -d test"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis #:6
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: mysecretpassword
    ports:
      - "6379:6379"
    # healthcheck:
      # test: ["CMD-SHELL", "pg_isready -U user -d test"]
      # interval: 10s
      # timeout: 5s
      # retries: 3
    command: ["redis-server", "--requirepass", "mysecretpassword"]

volumes:
  postgres_data: