env: "local"

redis:
    host:     "localhost"
    port:     6379
    password: "mysecretpassword"
    db:       0
  
postgres:
  driver:     "postgres"
  host:       "localhost"
  port:       5432
  username:   "postgres"
  password:   "mysecretpassword"
  sslmode:       "disable"
  db_name:           "postgres"
  max_open_conns: 25
  max_idle_conns: 25
  max_idle_time:  1m

server_auth:
  host:         "localhost"
  port:         9999
  timeout:      4s
  idle_timeout: 30s
  secret:       "secret" # серкрет для токена
  token_ttl:     1h # время для токена
  id_api:       1